name: TeamBattle
version: 1.1
author: LetsPeee
main: de.teamcreate.teambattle.TeamBattlePlugin
commands:
  teambattle:
    description: "§bAdministriere das TeamBattle"
    permission-message: "§cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
    aliases: tb
    usage: "§cSyntax Fehler! Verwende /<command> [start]"